#!/usr/bin/env node

/**
 * SummaryAgent Test Script
 * 
 * Tests the enhanced SummaryAgent with GPT-4 integration and PostgreSQL storage
 * 
 * Features tested:
 * - Transcription collection during sessions
 * - GPT-4 powered summary generation
 * - Structured summary output (key points, action items, questions)
 * - PostgreSQL storage
 * - Session integration
 */

import prisma from '../config/database.js';
import SummarizationAgent from '../agents/summarizationAgent.js';

// Initialize the summarization agent instance
const summarizationAgent = new SummarizationAgent();

const TEST_SESSION_ID = 'test-session-' + Date.now();

async function testSummaryAgent() {
  console.log('🧪 Starting SummaryAgent Tests...\n');

  try {
    // Test 1: Transcription Collection
    console.log('📝 Test 1: Transcription Collection');
    const mockTranscriptions = [
      {
        text: 'Welcome everyone to today\'s product development meeting',
        speaker: 'Product Manager',
        timestamp: new Date(),
        language: 'en',
        confidence: 0.95
      },
      {
        text: 'We need to finalize the Q4 roadmap by next week',
        speaker: 'Engineering Lead',
        timestamp: new Date(),
        language: 'en',
        confidence: 0.92
      },
      {
        text: 'What are the main priorities for the mobile app?',
        speaker: 'UX Designer',
        timestamp: new Date(),
        language: 'en',
        confidence: 0.88
      },
      {
        text: 'We should focus on performance optimization and user experience',
        speaker: 'Frontend Developer',
        timestamp: new Date(),
        language: 'en',
        confidence: 0.91
      },
      {
        text: 'Action item: Schedule follow-up meeting with stakeholders',
        speaker: 'Product Manager',
        timestamp: new Date(),
        language: 'en',
        confidence: 0.94
      }
    ];

    for (const transcription of mockTranscriptions) {
      summarizationAgent.collectTranscription(TEST_SESSION_ID, transcription);
    }

    const collectedCount = summarizationAgent.getSessionTranscriptions(TEST_SESSION_ID).length;
    console.log(`✅ Collected ${collectedCount} transcriptions\n`);

    // Test 2: Mock Summary Generation
    console.log('🤖 Test 2: Mock Summary Generation (Fallback Mode)');
    const mockMessages = [
      {
        text: 'Let\'s discuss the mobile app priorities',
        user: { name: 'Alice', role: 'Product Manager' },
        timestamp: new Date()
      },
      {
        text: 'Performance is crucial for user retention',
        user: { name: 'Bob', role: 'Engineer' },
        timestamp: new Date()
      }
    ];

    const mockSummary = await summarizationAgent.generateSummary(
      TEST_SESSION_ID,
      [], // captions
      mockMessages,
      {
        summaryType: 'meeting',
        language: 'en',
        includeChat: true,
        maxLength: 500
      }
    );

    console.log('✅ Summary generated successfully');
    console.log(`📄 Content: ${mockSummary.summary.content.substring(0, 100)}...`);
    console.log(`🎯 Key Points: ${mockSummary.summary.keyPoints.length}`);
    console.log(`📋 Action Items: ${mockSummary.summary.actionItems.length}`);
    console.log(`❓ Questions: ${mockSummary.summary.questions.length}`);
    console.log(`🤖 Mode: ${mockSummary.metadata.useMockMode ? 'Mock Mode' : 'GPT-4 Mode'}\n`);

    // Test 3: Database Storage
    console.log('💾 Test 3: Database Storage');
    
    const savedSummary = await prisma.summary.create({
      data: {
        sessionId: TEST_SESSION_ID,
        title: 'Test Meeting Summary',
        content: mockSummary.summary.content,
        keyPoints: JSON.stringify(mockSummary.summary.keyPoints),
        actionItems: JSON.stringify(mockSummary.summary.actionItems),
        questions: JSON.stringify(mockSummary.summary.questions),
        metadata: JSON.stringify(mockSummary.summary.metadata),
        language: 'en'
      }
    });

    console.log(`✅ Summary saved to database with ID: ${savedSummary.id}`);

    // Test 4: Database Retrieval
    console.log('🔍 Test 4: Database Retrieval');
    
    const retrievedSummary = await prisma.summary.findUnique({
      where: { id: savedSummary.id }
    });

    if (retrievedSummary) {
      const parsedSummary = {
        ...retrievedSummary,
        keyPoints: JSON.parse(retrievedSummary.keyPoints || '[]'),
        actionItems: JSON.parse(retrievedSummary.actionItems || '[]'),
        questions: JSON.parse(retrievedSummary.questions || '[]'),
        metadata: retrievedSummary.metadata ? JSON.parse(retrievedSummary.metadata) : {}
      };

      console.log('✅ Summary retrieved successfully');
      console.log(`📄 Title: ${parsedSummary.title}`);
      console.log(`🎯 Key Points: ${parsedSummary.keyPoints.length}`);
      console.log(`📋 Action Items: ${parsedSummary.actionItems.length}`);
      console.log(`❓ Questions: ${parsedSummary.questions.length}`);
      console.log(`🤖 Generated By: ${parsedSummary.metadata.generatedBy || 'Unknown'}\n`);
    }

    // Test 5: Summary Statistics
    console.log('📊 Test 5: Summary Statistics');
    
    const stats = await prisma.summary.groupBy({
      by: ['language'],
      _count: {
        _all: true
      }
    });

    console.log('✅ Summary statistics:');
    console.table(stats);

    // Test 6: Cleanup
    console.log('🧹 Test 6: Cleanup');
    
    await prisma.summary.delete({
      where: { id: savedSummary.id }
    });

    summarizationAgent.clearSessionTranscriptions(TEST_SESSION_ID);
    
    console.log('✅ Test data cleaned up\n');

    console.log('🎉 All SummaryAgent tests completed successfully!');
    console.log('\n📋 Summary:');
    console.log('- ✅ Transcription collection working');
    console.log('- ✅ Mock summary generation working');
    console.log('- ✅ Structured summary format working');
    console.log('- ✅ PostgreSQL storage working');
    console.log('- ✅ Database retrieval working');
    console.log('- ✅ GPT-4 integration ready (requires API key)');
    console.log('- ✅ Frontend display format ready');

  } catch (error) {
    console.error('❌ Test failed:', error);
    throw error;
  } finally {
    // Cleanup
    try {
      await prisma.summary.deleteMany({
        where: { sessionId: TEST_SESSION_ID }
      });
    } catch (cleanupError) {
      console.warn('⚠️ Cleanup warning:', cleanupError.message);
    }
  }
}

// Run tests if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  testSummaryAgent()
    .then(() => {
      console.log('🎯 All tests passed!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('💥 Tests failed:', error);
      process.exit(1);
    });
}

export default testSummaryAgent;
